baseURL: "https://mwgmac.github.io"
title: Matthew W. G. D. McClure
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: research
          url: research/
          weight: 5 

params:
    description: "Matthew on the web"
    author: MWGDM
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Matthew W. G. D. McClure
          subtitle: "Hi! I'm Matthew. I'm a PhD student in Philosophy at Cambridge (based at Peterhouse). Before that, I did an MA in Philosophy at Edinburgh, then an MPhil in Philosophy at Cambridge (also at Peterhouse).<br>
          
          I'm mostly at the moment working in philosophical logic and related areas, but I have other interests. Nonphilosophical interests include pubs and cute animals."

          imageUrl: "matthew.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: research
              url: research/

    socialIcons:
        - name: Email
          url: mailto:mwgm2@cam.ac.uk
        - name: LinkedIn
          url: https://www.linkedin.com/in/mwgmac/
        

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "M. W. G. D. McClure"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2